CREATE DATABASE BOARD_GAME

USE BOARD_GAME

-- BU TABLODA ÜLKE ÝSÝMLERÝ TUTULUR
CREATE TABLE tblUlke
(
	ULKE_ID CHAR(3) PRIMARY KEY,
	ULKE_AD VARCHAR(30) NOT NULL
)

-- BU TABLODA HER BÝR ÜLKEYE AÝT ÝL ÝSÝMLERÝ TUTULUR
CREATE TABLE tblIl
(
	KOD CHAR(2) PRIMARY KEY,
	IL_AD VARCHAR(30) NOT NULL,
	ULKE_ID CHAR(3) FOREIGN KEY REFERENCES tblUlke(ULKE_ID) NOT NULL
)
GO

-- BU TABLODA HER BÝR ÝLE AÝT ÝLÇELER TUTULUR
CREATE TABLE tblIlce
(
	ILCE_ID INT IDENTITY(1,1) PRIMARY KEY,
	ILCE_AD VARCHAR(30) NOT NULL,
	IL_KODU CHAR(2) FOREIGN KEY REFERENCES tblIl(KOD) NOT NULL
)
GO

-- BU TABLODA ADRES BÝLGÝLERÝ TUTULUR
CREATE TABLE tblAdres
(
	ADRES_ID INT IDENTITY(1,1) PRIMARY KEY,
	ADRES_AD VARCHAR(30) NOT NULL,
	ULKE_ID CHAR(3) FOREIGN KEY REFERENCES tblUlke(ULKE_ID) NOT NULL,
	IL_KODU CHAR(2) FOREIGN KEY REFERENCES tblIl(KOD) NOT NULL,
	ILCE_ID INT FOREIGN KEY REFERENCES tblIlce(ILCE_ID) NOT NULL
)
GO

-- BU TABLODA LOKASYON BÝLGÝLERÝ TUTULUR
CREATE TABLE tblLokasyon
(
	LOKASYON_ID INT IDENTITY(1,1) PRIMARY KEY,
	LOKAYSON_AD VARCHAR(30) NOT NULL,
	IRTIBAT_TELEFONU CHAR(10) UNIQUE,
	AKTIFLIK_DURUMU VARCHAR(20),
	ADRES_ID INT FOREIGN KEY REFERENCES tblAdres(ADRES_ID) NOT NULL
)
