CREATE DATABASE BOARD_GAME

USE BOARD_GAME

-- BU TABLODA ÜLKE İSİMLERİ TUTULUR
CREATE TABLE tblUlke
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ULKE_AD VARCHAR(30) NOT NULL
)
GO

-- BU TABLODA HER BİR ÜLKEYE AİT İL İSİMLERİ TUTULUR
CREATE TABLE tblIl
(
	KOD CHAR(2) PRIMARY KEY,
	IL_AD VARCHAR(30) NOT NULL,
	ULKE_ID INT FOREIGN KEY REFERENCES tblUlke(ID) NOT NULL
)
GO

-- BU TABLODA HER BİR İLE AİT İLÇELER TUTULUR
CREATE TABLE tblIlce
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ILCE_AD VARCHAR(30) NOT NULL,
	IL_KODU CHAR(2) FOREIGN KEY REFERENCES tblIl(KOD) NOT NULL
)
GO

-- BU TABLODA ADRES BİLGİLERİ TUTULUR
CREATE TABLE tblAdres
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ADRES_AD VARCHAR(30) NOT NULL,
	ULKE_ID INT FOREIGN KEY REFERENCES tblUlke(ID) NOT NULL,
	IL_KODU CHAR(2) FOREIGN KEY REFERENCES tblIl(KOD) NOT NULL,
	ILCE_ID INT FOREIGN KEY REFERENCES tblIlce(ID) NOT NULL
)
GO

-- BU TABLODA LOKASYON BİLGİLERİ TUTULUR
CREATE TABLE tblLokasyon
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LOKAYSON_AD VARCHAR(30) NOT NULL,
	IRTIBAT_TELEFONU VARCHAR(10) UNIQUE,
	AKTIFLIK_DURUMU VARCHAR(20),
	ADRES_ID INT FOREIGN KEY REFERENCES tblAdres(ID) NOT NULL
)
GO

-- PARA BİRİMİ
CREATE TABLE tblParaBirimi
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PARABIRIMI_AD VARCHAR(30) NOT NULL
)
GO

-- KOLEKSİYON
CREATE TABLE tblKoleksiyon
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	KOLEKSIYON_AD VARCHAR(30) NOT NULL,
	ODENEN_UCRET VARCHAR(10),
	PARABIRIMI_ID INT FOREIGN KEY REFERENCES tblParaBirimi(ID) NOT NULL,
	UYE_ID CHAR(3) FOREIGN KEY REFERENCES tblUye(ID) NOT NULL  -- ONCE UYE TABLOSUNU EKLEMEM GEREKİYOR
)
GO

CREATE TABLE tblKoleksiyonEklemeTuru
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	KOLEKSIYON_EKLEME_TURU_AD VARCHAR(30) NOT NULL
)
GO

CREATe TABLE tblEkle
(		
	ID INT IDENTITY(1,1) PRIMARY KEY,
	KOLEKSIYON_ID INT FOREIGN KEY REFERENCES tblKoleksiyon(ID) NOT NULL,
	KOLEKSIYON_EKLEME_TURU_ID INT FOREIGN KEY REFERENCES tblKoleksiyonEklemeTuru(ID) NOT NULL,

)
