CREATE DATABASE BOARD_GAME

USE BOARD_GAME

-- BU TABLO OYUN
CREATE TABLE tbloyun
(
  OYUN_ID INT IDENTITY(1,1) PRIMARY KEY,
  OYUN_ASILAD VARCHAR(30) NOT NULL
) 
GO

-- MEKANIK TABLOSU
CREATE TABLE tblmekanikler
(
 MEKANIK_ID INT IDENTITY(1,1) PRIMARY KEY,
 MAKANIK_AD VARCHAR(100) NOT NULL
)
GO

--KATEGORÝ TABLOSU
CREATE TABLE tblkategori
(
KATEGORI_ID INT IDENTITY(1,1) PRIMARY KEY,
KATEGORI_AD VARCHAR(100) NOT NULL
)
GO

--TÜR TABLOSU
CREATE TABLE tbltur
( 
TUR_ID INT IDENTITY(1,1) PRIMARY KEY,
TUR_AD VARCHAR(100) NOT NULL
)
GO

--TASARIMCI TABLOSU
CREATE TABLE tbltasarýmcý
( 
TASARIMCI_ID INT IDENTITY(1,1) PRIMARY KEY,
TASARIMCI_AD VARCHAR(100) NOT NULL,
TASARIMCI_SOYAD VARCHAR(100) NOT NULL
)
GO

--GÖREV ALANI TABLOSU
CREATE TABLE tblgorevalaný
( 
GOREVALANI_ID INT IDENTITY(1,1) PRIMARY KEY,
GOREVALANI_AD VARCHAR(100) NOT NULL
)
GO

-- OYUN VE MEKANÝKLER ÝLÝÞKÝ TABLOSU
CREATE TABLE tbloyunmekanikler(
 OYUNMEKANIK_ID INT IDENTITY(1,1) PRIMARY KEY,
 OYUN_ID INT FOREIGN KEY REFERENCES tbloyun(OYUN_ID) NOT NULL,
 MEKANIK_ID INT FOREIGN KEY REFERENCES tblmekanikler(MEKANIK_ID) NOT NULL
)
GO

-- OYUN VE KATEGORÝ TABLOSU
CREATE TABLE tbloyunkategori(
 OYUNKATEGORI_ID INT IDENTITY(1,1) PRIMARY KEY,
 OYUN_ID INT FOREIGN KEY REFERENCES tbloyun(OYUN_ID) NOT NULL,
 KATEGORI_ID INT FOREIGN KEY REFERENCES tblkategori(KATEGORI_ID) NOT NULL
)
GO

-- OYUN VE TÜR TABLOSU
CREATE TABLE tbloyuntur(
 OYUNTUR_ID INT IDENTITY(1,1) PRIMARY KEY,
 OYUN_ID INT FOREIGN KEY REFERENCES tbloyun(OYUN_ID) NOT NULL,
 TUR_ID INT FOREIGN KEY REFERENCES tbltur(TUR_ID) NOT NULL
)
GO

-- OYUN VE TASARIMCI TABLOSU
CREATE TABLE tbloyuntasarimci(
 OYUNTASARIMCI_ID INT IDENTITY(1,1) PRIMARY KEY,
 OYUN_ID INT FOREIGN KEY REFERENCES tbloyun(OYUN_ID) NOT NULL,
 TASARIMCI_ID INT FOREIGN KEY REFERENCES tbltasarýmcý(TASARIMCI_ID) NOT NULL
)
GO

-- TASARIMCI VE GÖREV ALANI TABLOSU
CREATE TABLE tbltasarimgorevalani(
 TASARIMGOREVALANI_ID INT IDENTITY(1,1) PRIMARY KEY,
 TASARIMCI_ID INT FOREIGN KEY REFERENCES tbltasarýmcý(TASARIMCI_ID) NOT NULL,
 GOREVALANI_ID INT FOREIGN KEY REFERENCES tblgorevalaný(GOREVALANI_ID) NOT NULL
)
GO